<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- ESTA ES LA LÍNEA QUE CAMBIÓ -->
    <TargetFramework>net9.0-windows</TargetFramework>
    
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <!-- Soporte para Windows Forms -->
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDataReader" Version="3.8.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.7" />
    
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
  </ItemGroup>
  <ItemGroup>
    <None Update="taller.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>